server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/printerapp
    username: printerapp
    password: printerapp
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

outbound:
  identity:
    client-id: "904914536933-rn9iprnahvv77p78n2j7stuiinmjfqp9.apps.googleusercontent.com"
    client-secret: "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"
    redirect-uri: "http://localhost:3000/authenticate"
    grant-type: "authorization-code"