server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/printerapp
    username: printerapp
    password: printerapp
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true